apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xzsbfbact-go 
  janus-idp.io/tekton: xzsbfbact-go
  backstage.io/kubernetes-id: xzsbfbact-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xzsbfbact-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  